// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHych9-z_0wetZejugOcxU6DaELdu4gdY',
    appId: '1:969473750560:web:134196303975892fefae45',
    messagingSenderId: '969473750560',
    projectId: 'loginapp-be4b7',
    authDomain: 'loginapp-be4b7.firebaseapp.com',
    storageBucket: 'loginapp-be4b7.appspot.com',
    measurementId: 'G-0RYLWDPX05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZEsa4EVLAKMeas3QzawMjVS7oyN8yuWY',
    appId: '1:969473750560:android:dc3ec1814fd9f07eefae45',
    messagingSenderId: '969473750560',
    projectId: 'loginapp-be4b7',
    storageBucket: 'loginapp-be4b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMCtUxDD4MA_xXYYHefCX0dc1Pg7c44q4',
    appId: '1:969473750560:ios:4927135677e2700cefae45',
    messagingSenderId: '969473750560',
    projectId: 'loginapp-be4b7',
    storageBucket: 'loginapp-be4b7.appspot.com',
    iosBundleId: 'com.example.loginpage',
  );
}
